#!/usr/bin/env python3
"""Opt-in scene567 path experiment. Generated GPL source stays in reports."""
import argparse
import json
import math
import os
from pathlib import Path
import subprocess
import time

from run_mandel_ifs_precision import (ROOT, SUPPORT, SCENE_SHA, FORMULA_SHA,
    config_values, field_source, import_formula, scalar, vector)
from run_release_canaries import sha256


def path_source(cfg, formula, arithmetic):
    source = field_source(formula, cfg, arithmetic)
    source = source.replace('using R = fpt_precision::Scalar;',
                            'namespace fpt_ifs {\nusing R = fpt_precision::Scalar;', 1)
    path = (SUPPORT/'IfsPath.metal').read_text()
    for key, value in {'@ORIGIN@': vector(cfg['camera']), '@VIEW_MAX@': scalar(cfg['controls'][6]),
                       '@REFINE_RATIO@': scalar(.998), '@COLOR_BAILOUT@': scalar(1e15),
                       '@ORBIT_EPS@': scalar(1e-15), '@MIN_THRESHOLD@': scalar(1e-12),
                       '@NORMAL_SCALE@': scalar(.1)}.items():
        path = path.replace(key, value)
    if '@' in path:
        raise ValueError('unexpanded precision path')
    return source + path + '\n} // namespace fpt_ifs\n'


def shifted_camera(cfg, shift):
    """Translate eye/target together in native camera-plane focus-distance units."""
    if len(shift)!=2 or not all(math.isfinite(v) and abs(v)<=.5 for v in shift):
        raise ValueError('camera shift must be finite and within +/-0.5 focus distances')
    def normalize(v):
        length=math.sqrt(sum(x*x for x in v))
        if not math.isfinite(length) or length<=0: raise ValueError('invalid camera basis')
        return [x/length for x in v]
    def cross(a,b):
        return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]
    view=[b-a for a,b in zip(cfg['camera'],cfg['target'])]
    distance=math.sqrt(sum(v*v for v in view))
    forward=normalize(view)
    right=normalize(cross(forward,cfg['top']))
    up=normalize(cross(right,forward))
    offset=[distance*(shift[0]*r+shift[1]*u) for r,u in zip(right,up)]
    result={k:list(v) for k,v in cfg.items()}
    for name in ('camera','target'):
        result[name]=[v+d for v,d in zip(cfg[name],offset)]
    return result,dict(shift_focus_distances=list(shift),native_offset=offset,
        source_camera=cfg['camera'],camera=result['camera'],target=result['target'],top=result['top'])


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--scene', type=Path, required=True)
    p.add_argument('--mandelbulber-root', type=Path, required=True)
    p.add_argument('--fpt-inputs', type=Path, help='Optional cached input directory; otherwise generated by FPT Rust parser')
    p.add_argument('--out', type=Path, required=True)
    p.add_argument('--precision', '--arithmetic', dest='arithmetic', choices=('three','two'), default='three')
    p.add_argument('--control', choices=('headlight','authored'), default='headlight')
    p.add_argument('--size', default='32x18')
    p.add_argument('--samples', type=int, default=1)
    p.add_argument('--bounces', type=int, choices=range(1,9), default=2)
    p.add_argument('--camera-shift', default='0,0', help='right,up translation in focus-distance units; no rotation')
    p.add_argument('--tile-rows',type=int,choices=range(1,33),default=8)
    args = p.parse_args()
    width,height=map(int,args.size.split('x'))
    if not (0<width<=320 and 0<height<=240 and 0<args.samples<=32):
        raise ValueError('bounded diagnostic size/samples required')
    if args.arithmetic=='three' and width*height>1024:
        raise ValueError('three-term full-path dispatch limited to 1024 pixels')
    formula_path=args.mandelbulber_root/'formula/definition/fractal_kaleidoscopic_ifs.cpp'
    if sha256(args.scene)!=SCENE_SHA or sha256(formula_path)!=FORMULA_SHA:
        raise ValueError('unsupported scene/formula')
    # Validate before creating any output, including the uncached-input route.
    shift=tuple(map(float,args.camera_shift.split(',')))
    if len(shift)!=2 or not all(math.isfinite(v) and abs(v)<=.5 for v in shift):
        raise ValueError('invalid bounded camera shift')
    args.out.mkdir(parents=True,exist_ok=False)
    out=args.out.resolve()
    if args.fpt_inputs is None:
        args.fpt_inputs=out/'inputs'
        input_command=[str(ROOT/'target/release/examples/mandel_ifs_precision_inputs'),str(args.scene),
            str(args.fpt_inputs),args.size,'center']
        result=subprocess.run(input_command,capture_output=True,text=True,timeout=60)
        (out/'input-command.json').write_text(json.dumps(input_command,indent=2)+'\n')
        (out/'input-stdout.log').write_text(result.stdout)
        (out/'input-stderr.log').write_text(result.stderr)
        if result.returncode: raise RuntimeError(result.stderr)
    inputs=json.loads((args.fpt_inputs/'summary.json').read_text())
    if sha256(args.scene)!=SCENE_SHA or sha256(formula_path)!=FORMULA_SHA or inputs['scene_sha256']!=SCENE_SHA:
        raise ValueError('unsupported scene/formula')
    if sha256(args.fpt_inputs/'config.tsv')!=inputs['config_sha256']:
        raise ValueError('FPT config identity mismatch')
    cfg,camera=shifted_camera(config_values(args.fpt_inputs/'config.tsv'),shift)
    helper=out/'ifs-path.metal'
    helper.write_text(path_source(cfg,import_formula(formula_path,cfg),args.arithmetic))
    env=os.environ.copy()
    env['FPT_IFS_PRECISION_SOURCE']=str(helper)
    env['FPT_MANDEL_TILED_DISPATCH']='1'
    env['FPT_MANDEL_TILE_ROWS']=str(args.tile_rows)
    env.pop('FPT_IFS_PRECISION_HEADLIGHT',None)
    if args.control=='headlight': env['FPT_IFS_PRECISION_HEADLIGHT']='1'
    command=[str(ROOT/'target/release/examples/mandel_derivative_render'),'beauty',str(args.scene),
        '--mandelbulber-root',str(args.mandelbulber_root),'--width',str(width),'--height',str(height),
        '--samples',str(args.samples),'--sdf-accumulation','chunked','--sdf-chunk-samples','1',
        '--mandel-appearance','authored-path','--sdf-bounce-cap',str(args.bounces),'--out',str(out/'render')]
    start=time.monotonic()
    result=subprocess.run(command,env=env,capture_output=True,text=True,timeout=900)
    (out/'stdout.log').write_text(result.stdout)
    (out/'stderr.log').write_text(result.stderr)
    report=dict(command=command,arithmetic=args.arithmetic,control=args.control,scene_sha256=SCENE_SHA,
        formula_sha256=FORMULA_SHA,helper_sha256=sha256(helper),wall_s=time.monotonic()-start,
        returncode=result.returncode,exclusions=['AO','fog','clouds','glow'],production_unchanged=True,
        camera=camera,tile_rows=args.tile_rows,input_config_sha256=inputs['config_sha256'])
    (out/'run.json').write_text(json.dumps(report,indent=2)+'\n')
    if result.returncode:
        raise RuntimeError(result.stderr[-8000:])
    print(json.dumps(report,indent=2))


if __name__=='__main__':
    main()
